import React from 'react';
// For modern React (version 18+), we import the client from 'react-dom/client'
import ReactDOM from 'react-dom/client';
import App from './App'; // This imports the Vibe Commerce Cart component

// If you have a global stylesheet (like one generated by create-react-app or Vite),
// you would include the import here:
// import './index.css';

// Get the main mounting point element from the public/index.html file
const rootElement = document.getElementById('root');

// Create a root for the application using React 18's concurrent mode
const root = ReactDOM.createRoot(rootElement);

// Render the main App component into the root
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
